### ISSUE TITLE
clean up lingering tiff issues on Google Drive

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#19]
It looks like there are some files that need attention:

- `286 (1).tiff`
- `253-old.tiff`
- `303 (1).tiff`

**Comment by nicholasjhorton** [comment]
@kjinsanity might you be willing to take the lead on tracking down these remaining issues (lest they bleed into the other folders on Google Drive)? 

Thanks in advance, Nick

**Comment by NahiaP** [comment]
While converting, I noted in #2 that 253-old.tiff was a duplicate of 253.tiff 

Maybe one should be deleted?

**Comment by nicholasjhorton** [comment]
If it's a duplicate (and `253.tiff` is a better scan) then the old file should be deleted. @kjinsanity can you please take a look at this and the other dups?

**Comment by nicholasjhorton** [comment]
I've taken care of `253-old.tiff` in the `tiff` and `tiff_processing` folders.

286 and 286 (1) raise some interesting question. One has a string to hold it down and the other is at an angle. Let's talk.

**Comment by kjinsanity** [comment]
> 286 and 286 (1) raise some interesting question. One has a string to hold it down and the other is at an angle. Let's talk.

Regarding 286 and 286 (1), I believe that for consistency's sake that 286 (the one without the string) is better because it matches the style of the other pictures. If the angle is an issue, then page 288 also seems to be at an angle as well, and the detail of the string may cause an unknowing viewer to think there may be a significance to the string on that page only 

> Regarding `303 (1).tiff`

I believe that `303.tiff` is a better image as it does seem to contain extra information on the scrap that is not present in 303 (1). Looking at page 305, that information isn't there, so for sake of preservation, I think it should be important to keep it.

**Comment by nicholasjhorton** [comment]
I concur with @kjinsanity's assessments. I moved the other images into `raw_deleted` on Google Drive.
